apiVersion: v1
kind: Secret
metadata:
  name: coffee-app-secret
type: Opaque
stringData:
  JWT_SECRET: "change-this-secret"
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  FACEBOOK_CLIENT_ID: ""
  FACEBOOK_CLIENT_SECRET: ""
